services:
  web:
    build: .
    container_name: pj_app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
      DATABASE_URL: "sqlite3:/app/db/development.sqlite3"

